-- File này dùng để khởi tạo dữ liệu provider mô hình, không cần thực thi thủ công, sẽ tự động thực thi khi khởi động dự án
-- --------------------------------------------------------
-- Khởi tạo dữ liệu provider mô hình
DELETE FROM `ai_model_provider`;
INSERT INTO `ai_model_provider` (`id`, `model_type`, `provider_code`, `name`, `fields`, `sort`, `creator`, `create_date`, `updater`, `update_date`) VALUES
-- Provider mô hình VAD
('SYSTEM_VAD_SileroVAD', 'VAD', 'silero', 'Phát hiện hoạt động giọng nói SileroVAD', '[{"key":"threshold","label":"Ngưỡng phát hiện","type":"number"},{"key":"model_dir","label":"Thư mục mô hình","type":"string"},{"key":"min_silence_duration_ms","label":"Thời lượng im lặng tối thiểu","type":"number"}]', 1, 1, NOW(), 1, NOW()),

-- Provider mô hình ASR
('SYSTEM_ASR_FunASR', 'ASR', 'fun_local', 'Nhận dạng giọng nói FunASR', '[{"key":"model_dir","label":"Thư mục mô hình","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_ASR_SherpaASR', 'ASR', 'sherpa_onnx_local', 'Nhận dạng giọng nói SherpaASR', '[{"key":"model_dir","label":"Thư mục mô hình","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_ASR_DoubaoASR', 'ASR', 'doubao', 'Nhận dạng giọng nói Núi Lửa', '[{"key":"appid","label":"ID ứng dụng","type":"string"},{"key":"access_token","label":"Token truy cập","type":"string"},{"key":"cluster","label":"Cluster","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 3, 1, NOW(), 1, NOW()),

-- Provider mô hình LLM
('SYSTEM_LLM_openai', 'LLM', 'openai', 'Giao diện OpenAI', '[{"key":"base_url","label":"URL cơ sở","type":"string"},{"key":"model_name","label":"Tên mô hình","type":"string"},{"key":"api_key","label":"Khóa API","type":"string"},{"key":"temperature","label":"Nhiệt độ","type":"number"},{"key":"max_tokens","label":"Số token tối đa","type":"number"},{"key":"top_p","label":"Giá trị top_p","type":"number"},{"key":"top_k","label":"Giá trị top_k","type":"number"},{"key":"frequency_penalty","label":"Phạt tần suất","type":"number"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_AliBL', 'LLM', 'AliBL', 'Giao diện Alibaba Bách Luyện', '[{"key":"base_url","label":"URL cơ sở","type":"string"},{"key":"app_id","label":"ID ứng dụng","type":"string"},{"key":"api_key","label":"Khóa API","type":"string"},{"key":"is_no_prompt","label":"Có không sử dụng prompt local không","type":"boolean"},{"key":"ali_memory_id","label":"ID nhớ","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_ollama', 'LLM', 'ollama', 'Giao diện Ollama', '[{"key":"model_name","label":"Tên mô hình","type":"string"},{"key":"base_url","label":"Địa chỉ dịch vụ","type":"string"}]', 3, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_dify', 'LLM', 'dify', 'Giao diện Dify', '[{"key":"base_url","label":"URL cơ sở","type":"string"},{"key":"api_key","label":"Khóa API","type":"string"},{"key":"mode","label":"Chế độ hội thoại","type":"string"}]', 4, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_gemini', 'LLM', 'gemini', 'Giao diện Gemini', '[{"key":"api_key","label":"Khóa API","type":"string"},{"key":"model_name","label":"Tên mô hình","type":"string"},{"key":"http_proxy","label":"Proxy HTTP","type":"string"},{"key":"https_proxy","label":"Proxy HTTPS","type":"string"}]', 5, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_coze', 'LLM', 'coze', 'Giao diện Coze', '[{"key":"bot_id","label":"ID robot","type":"string"},{"key":"user_id","label":"ID người dùng","type":"string"},{"key":"personal_access_token","label":"Token truy cập cá nhân","type":"string"}]', 6, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_fastgpt', 'LLM', 'fastgpt', 'Giao diện FastGPT', '[{"key":"base_url","label":"URL cơ sở","type":"string"},{"key":"api_key","label":"Khóa API","type":"string"},{"key":"variables","label":"Biến","type":"dict","dict_name":"variables"}]', 7, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_xinference', 'LLM', 'xinference', 'Giao diện Xinference', '[{"key":"model_name","label":"Tên mô hình","type":"string"},{"key":"base_url","label":"Địa chỉ dịch vụ","type":"string"}]', 8, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_doubao', 'LLM', 'doubao', 'LLM Núi Lửa', '[{"key":"base_url","label":"URL cơ sở","type":"string"},{"key":"model_name","label":"Tên mô hình","type":"string"},{"key":"api_key","label":"Khóa API","type":"string"}]', 9, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_chatglm', 'LLM', 'chatglm', 'Giao diện ChatGLM', '[{"key":"model_name","label":"Tên mô hình","type":"string"},{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"api_key","label":"Khóa API","type":"string"}]', 10, 1, NOW(), 1, NOW()),

-- Provider mô hình TTS
('SYSTEM_TTS_edge', 'TTS', 'edge', 'Edge TTS', '[{"key":"voice","label":"Giọng","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_doubao', 'TTS', 'doubao', 'TTS Núi Lửa', '[{"key":"api_url","label":"Địa chỉ API","type":"string"},{"key":"voice","label":"Giọng","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"authorization","label":"Ủy quyền","type":"string"},{"key":"appid","label":"ID ứng dụng","type":"string"},{"key":"access_token","label":"Token truy cập","type":"string"},{"key":"cluster","label":"Cluster","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_siliconflow', 'TTS', 'siliconflow', 'TTS Silicon Flow', '[{"key":"model","label":"Mô hình","type":"string"},{"key":"voice","label":"Giọng","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"access_token","label":"Token truy cập","type":"string"},{"key":"response_format","label":"Định dạng phản hồi","type":"string"}]', 3, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_cozecn', 'TTS', 'cozecn', 'COZECN TTS', '[{"key":"voice","label":"Giọng","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"access_token","label":"Token truy cập","type":"string"},{"key":"response_format","label":"Định dạng phản hồi","type":"string"}]', 4, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_fishspeech', 'TTS', 'fishspeech', 'FishSpeech TTS', '[{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"response_format","label":"Định dạng phản hồi","type":"string"},{"key":"reference_id","label":"ID tham chiếu","type":"string"},{"key":"reference_audio","label":"Âm thanh tham chiếu","type":"dict","dict_name":"reference_audio"},{"key":"reference_text","label":"Văn bản tham chiếu","type":"dict","dict_name":"reference_text"},{"key":"normalize","label":"Có chuẩn hóa không","type":"boolean"},{"key":"max_new_tokens","label":"Số token mới tối đa","type":"number"},{"key":"chunk_length","label":"Độ dài khối","type":"number"},{"key":"top_p","label":"Giá trị top_p","type":"number"},{"key":"repetition_penalty","label":"Phạt lặp lại","type":"number"},{"key":"temperature","label":"Nhiệt độ","type":"number"},{"key":"streaming","label":"Có streaming không","type":"boolean"},{"key":"use_memory_cache","label":"Có sử dụng cache bộ nhớ không","type":"string"},{"key":"seed","label":"Hạt giống","type":"number"},{"key":"channels","label":"Số kênh","type":"number"},{"key":"rate","label":"Tần số lấy mẫu","type":"number"},{"key":"api_key","label":"Khóa API","type":"string"},{"key":"api_url","label":"Địa chỉ API","type":"string"}]', 5, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gpt_sovits_v2', 'TTS', 'gpt_sovits_v2', 'GPT-SoVITS V2', '[{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"text_lang","label":"Ngôn ngữ văn bản","type":"string"},{"key":"ref_audio_path","label":"Đường dẫn âm thanh tham chiếu","type":"string"},{"key":"prompt_text","label":"Văn bản prompt","type":"string"},{"key":"prompt_lang","label":"Ngôn ngữ prompt","type":"string"},{"key":"top_k","label":"Giá trị top_k","type":"number"},{"key":"top_p","label":"Giá trị top_p","type":"number"},{"key":"temperature","label":"Nhiệt độ","type":"number"},{"key":"text_split_method","label":"Phương pháp phân tách văn bản","type":"string"},{"key":"batch_size","label":"Kích thước batch","type":"number"},{"key":"batch_threshold","label":"Ngưỡng batch","type":"number"},{"key":"split_bucket","label":"Có phân nhóm không","type":"boolean"},{"key":"return_fragment","label":"Có trả về đoạn không","type":"boolean"},{"key":"speed_factor","label":"Hệ số tốc độ","type":"number"},{"key":"streaming_mode","label":"Có chế độ streaming không","type":"boolean"},{"key":"seed","label":"Hạt giống","type":"number"},{"key":"parallel_infer","label":"Có suy luận song song không","type":"boolean"},{"key":"repetition_penalty","label":"Phạt lặp lại","type":"number"},{"key":"aux_ref_audio_paths","label":"Đường dẫn âm thanh tham chiếu phụ","type":"dict","dict_name":"aux_ref_audio_paths"}]', 6, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gpt_sovits_v3', 'TTS', 'gpt_sovits_v3', 'GPT-SoVITS V3', '[{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"text_language","label":"Ngôn ngữ văn bản","type":"string"},{"key":"refer_wav_path","label":"Đường dẫn âm thanh tham chiếu","type":"string"},{"key":"prompt_language","label":"Ngôn ngữ prompt","type":"string"},{"key":"prompt_text","label":"Văn bản prompt","type":"string"},{"key":"top_k","label":"Giá trị top_k","type":"number"},{"key":"top_p","label":"Giá trị top_p","type":"number"},{"key":"temperature","label":"Nhiệt độ","type":"number"},{"key":"cut_punc","label":"Dấu câu cắt","type":"string"},{"key":"speed","label":"Tốc độ","type":"number"},{"key":"inp_refs","label":"Tham chiếu đầu vào","type":"dict","dict_name":"inp_refs"},{"key":"sample_steps","label":"Số bước lấy mẫu","type":"number"},{"key":"if_sr","label":"Có sử dụng SR không","type":"boolean"}]', 7, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_minimax', 'TTS', 'minimax', 'Minimax TTS', '[{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"group_id","label":"ID nhóm","type":"string"},{"key":"api_key","label":"Khóa API","type":"string"},{"key":"model","label":"Mô hình","type":"string"},{"key":"voice_id","label":"ID giọng","type":"string"}]', 8, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_aliyun', 'TTS', 'aliyun', 'TTS Alibaba Cloud', '[{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"appkey","label":"Khóa ứng dụng","type":"string"},{"key":"token","label":"Token truy cập","type":"string"},{"key":"voice","label":"Giọng","type":"string"},{"key":"access_key_id","label":"ID khóa truy cập","type":"string"},{"key":"access_key_secret","label":"Mật khẩu khóa truy cập","type":"string"}]', 9, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_ttson', 'TTS', 'ttson', 'ACGNTTS', '[{"key":"token","label":"Token truy cập","type":"string"},{"key":"voice_id","label":"ID giọng","type":"string"},{"key":"speed_factor","label":"Hệ số tốc độ","type":"number"},{"key":"pitch_factor","label":"Hệ số độ cao giọng","type":"number"},{"key":"volume_change_dB","label":"Thay đổi âm lượng","type":"number"},{"key":"to_lang","label":"Ngôn ngữ đích","type":"string"},{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"format","label":"Định dạng","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"emotion","label":"Cảm xúc","type":"number"}]', 10, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_openai', 'TTS', 'openai', 'OpenAI TTS', '[{"key":"api_key","label":"Khóa API","type":"string"},{"key":"api_url","label":"Địa chỉ API","type":"string"},{"key":"model","label":"Mô hình","type":"string"},{"key":"voice","label":"Giọng","type":"string"},{"key":"speed","label":"Tốc độ","type":"number"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 11, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_custom', 'TTS', 'custom', 'TTS tùy chỉnh', '[{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"params","label":"Tham số yêu cầu","type":"dict","dict_name":"params"},{"key":"headers","label":"Header yêu cầu","type":"dict","dict_name":"headers"},{"key":"format","label":"Định dạng âm thanh","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 12, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_302ai', 'TTS', '302ai', '302AI TTS', '[{"key":"api_url","label":"Địa chỉ API","type":"string"},{"key":"authorization","label":"Ủy quyền","type":"string"},{"key":"voice","label":"Giọng","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"access_token","label":"Token truy cập","type":"string"}]', 13, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gizwits', 'TTS', 'gizwits', 'TTS Gizwits', '[{"key":"api_url","label":"Địa chỉ API","type":"string"},{"key":"authorization","label":"Ủy quyền","type":"string"},{"key":"voice","label":"Giọng","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"access_token","label":"Token truy cập","type":"string"}]', 14, 1, NOW(), 1, NOW()),

-- Provider mô hình Memory
('SYSTEM_Memory_mem0ai', 'Memory', 'mem0ai', 'Nhớ Mem0AI', '[{"key":"api_key","label":"Khóa API","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_Memory_nomem', 'Memory', 'nomem', 'Không nhớ', '[]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_Memory_mem_local_short', 'Memory', 'mem_local_short', 'Nhớ ngắn local', '[]', 3, 1, NOW(), 1, NOW()),

-- Provider mô hình Intent
('SYSTEM_Intent_nointent', 'Intent', 'nointent', 'Không nhận dạng ý định', '[]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_Intent_intent_llm', 'Intent', 'intent_llm', 'Nhận dạng ý định LLM', '[{"key":"llm","label":"Mô hình LLM","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_Intent_function_call', 'Intent', 'function_call', 'Nhận dạng ý định gọi hàm', '[{"key":"functions","label":"Danh sách hàm","type":"dict","dict_name":"functions"}]', 3, 1, NOW(), 1, NOW());
